const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  const flights = [
    {
      flightNumber: "6E 5177",
      airline: "Indigo",
      departureAirportCode: "DEL",
      departureAirportName: "Delhi Indira Gandhi International Airport",
      arrivalAirportCode: "HYD",
      arrivalAirportName: "Hyderabad Rajiv Gandhi International Airport",
      date: new Date('2024-07-27'),
      departureTime: new Date('2024-07-27T13:30:00Z'),
      arrivalTime: new Date('2024-07-27T15:40:00Z'),
      status: "On Time",
      gate: "35A",
      terminal: "3",
      scheduledDepartureTime: new Date('2024-07-27T13:30:00Z'),
      scheduledArrivalTime: new Date('2024-07-27T15:40:00Z'),
      elapsedTime: 0,
      aircraftType: "A320",
      baggageClaim: "",
      remarks: "Boarding starts at 13:00",
      isInternational: false,
      lastUpdated: new Date(),
    },
    {
      flightNumber: "6E 5257",
      airline: "Indigo",
      departureAirportCode: "DEL",
      departureAirportName: "Delhi Indira Gandhi International Airport",
      arrivalAirportCode: "BLR",
      arrivalAirportName: "Bengaluru Kempegowda International Airport",
      date: new Date('2024-07-27'),
      departureTime: new Date('2024-07-27T12:55:00Z'),
      arrivalTime: new Date('2024-07-27T15:40:00Z'),
      status: "On Time",
      gate: "41",
      terminal: "3",
      scheduledDepartureTime: new Date('2024-07-27T12:55:00Z'),
      scheduledArrivalTime: new Date('2024-07-27T15:40:00Z'),
      elapsedTime: 0,
      aircraftType: "A320",
      baggageClaim: "",
      remarks: "Boarding starts at 12:15",
      isInternational: false,
      lastUpdated: new Date(),
    },
    {
      flightNumber: "6E 2009",
      airline: "Indigo",
      departureAirportCode: "DEL",
      departureAirportName: "Delhi Indira Gandhi International Airport",
      arrivalAirportCode: "BOM",
      arrivalAirportName: "Mumbai Chhatrapati Shivaji International Airport",
      date: new Date('2024-07-27'),
      departureTime: new Date('2024-07-27T12:30:00Z'),
      arrivalTime: new Date('2024-07-27T14:40:00Z'),
      status: "On Time",
      gate: "T30",
      terminal: "2",
      scheduledDepartureTime: new Date('2024-07-27T12:30:00Z'),
      scheduledArrivalTime: new Date('2024-07-27T14:40:00Z'),
      elapsedTime: 0,
      aircraftType: "A320",
      baggageClaim: "",
      remarks: "Boarding starts at 11:45",
      isInternational: false,
      lastUpdated: new Date(),
    },
    {
      flightNumber: "6E 2315",
      airline: "Indigo",
      departureAirportCode: "DEL",
      departureAirportName: "Delhi Indira Gandhi International Airport",
      arrivalAirportCode: "COK",
      arrivalAirportName: "Cochin International Airport",
      date: new Date('2024-07-27'),
      departureTime: new Date('2024-07-27T12:55:00Z'),
      arrivalTime: new Date('2024-07-27T16:00:00Z'),
      status: "On Time",
      gate: "T32",
      terminal: "2",
      scheduledDepartureTime: new Date('2024-07-27T12:55:00Z'),
      scheduledArrivalTime: new Date('2024-07-27T16:00:00Z'),
      elapsedTime: 0,
      aircraftType: "A320",
      baggageClaim: "",
      remarks: "Boarding starts at 12:15",
      isInternational: false,
      lastUpdated: new Date(),
    },
    {
      flightNumber: "6E 2196",
      airline: "Indigo",
      departureAirportCode: "DEL",
      departureAirportName: "Delhi Indira Gandhi International Airport",
      arrivalAirportCode: "IXC",
      arrivalAirportName: "Chandigarh Airport",
      date: new Date('2024-07-27'),
      departureTime: new Date('2024-07-27T14:55:00Z'),
      arrivalTime: new Date('2024-07-27T16:00:00Z'),
      status: "On Time",
      gate: "T22",
      terminal: "2",
      scheduledDepartureTime: new Date('2024-07-27T14:55:00Z'),
      scheduledArrivalTime: new Date('2024-07-27T16:00:00Z'),
      elapsedTime: 0,
      aircraftType: "A320",
      baggageClaim: "",
      remarks: "Boarding starts at 14:00",
      isInternational: false,
      lastUpdated: new Date(),
    }
  ];

  await prisma.flight.createMany({ data: flights });
  console.log("Flight data seeded successfully!");
}

main()
  .catch(e => console.error(e))
  .finally(async () => {
    await prisma.$disconnect();
  });
